<?php // $Id$

define (BRLCAD_NODETYPE, 'model');

/**
 * Implementation of hook_menu
 */
function brlcad_menu($may_cache) {
  $links = array();
  if($may_cache) {
      
  } else {
    $links[] = array(
      'path' => 'admin/content/brlcad',
      'title' => t('BRL-CAD'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('brlcad_general_settings'),
    );
  }
  return $links;
}

/**
 * Implementation of hook_cron
 */
function brlcad_cron() {
  brlcad_process_nodes();
}

/**
 * General settings form for BRL-CAD.
 */
function brlcad_general_settings() {
  $flags = flag_get_flags('node', BRLCAD_NODETYPE);
  foreach($flags as $flag => $data) {
    $flags[$flag] = $data->title;
  }
  $form = array();
  $form['system'] = array(
    '#type' => 'fieldset',
    '#title' => t('BRL-CAD system'),
    '#tree' => false,
  );
  $form['system']['brlcad_version'] = array(
    '#type' => 'select',
    '#title' => t('Version'),
    '#options' => _brlcad_supported_versions(),
    '#default_value' => variable_get('brlcad_version', '7.14'),
    '#required' => true,
  );
  $form['system']['brlcad_bin_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to binaries'),
    '#default_value' => variable_get('brlcad_bin_path', '/usr/brlcad/bin'),
    '#required' => true,
  );
  $form['system']['brlcad_processing_flag'] = array(
    '#title' => t('BRL-CAD processing'),  
    '#type' => 'select',
    '#options' => $flags,
    '#default_value' => variable_get('brlcad_processing_flag', ''),
    '#description' => t('Select the flag which marks the nodes that require BRL-CAD specific processing.'),
  );
  $form['raytrace'] = array(
    '#type' => 'fieldset',
    '#title' => t('Raytracing'),
    '#tree' => false,
  );
  $form['raytrace']['brlcad_raytrace_ae'] = array(
    '#type' => 'textarea',
    '#title' => 'Views',
    '#description' => t('Enter raytracing azimuth elevation (and optionally twist) tuples for raytracing, one per line. An image will be generated for each tuple.'),
    '#default_value' => variable_get('brlcad_raytrace_ae', ''),
  );
  $form['raytrace']['brlcad_raytrace_size'] = array(
    '#type' => 'textfield',
    '#title' => 'Size',
    '#description' => t('Enter number of pixels of the image.'),
    '#default_value' => variable_get('brlcad_raytrace_size', 512),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_nodeapi
 */
function brlcad_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if($node->type != BRLCAD_NODETYPE) {
    return;
  }
  switch($op) {
    default:
      break;
    case 'submit_no':
      brlcad_metadata($node);
      break;
    case 'view_no':
      dvm(brlcad_objects_list($node->field_objects[0]['value']));
      dvm($node->field_render_objects);
      break;
  }
}

/**
 * Implementation hook of filefield. 
 */
function brlcad_filefield($op, &$node, &$field, &$file) {
  if($op == 'file_save' && $field['field_name'] == 'field_model_file') {
    brlcad_processing_flag($node, true);
  }
}

function brlcad_processing_flag(&$node, $enable_flag) {
  $flag = flag_get_flag(variable_get('brlcad_processing_flag', '')); 
  if (!$flag || $flag->is_flagged($node->nid) == $enable_flag) {
    // Flag does not exist.
    return FALSE;
  }
  if($enable_flag) {
    drupal_set_message(t('Your model was queued for further processing with BRL-CAD tools (raytracing, metadata extraction, etc). Upon completion, it will be updated with additional data.'));
    return $flag->flag('flag', $node->nid, _brlcad_fakeuser());
  } else {
    return $flag->flag('unflag', $node->nid, _brlcad_fakeuser());
  }
}

/**
 * Implementation of hook_alter
 */
function brlcad_form_alter($form_id, &$form) {
  if($form_id != BRLCAD_NODETYPE . '_node_form') {
    return;
  }
  if(arg(0) == 'node') {
    unset($form['group_metadata']);
  }
  return;
  $hidden = array(
    0 => array('field_image_file', 'body_filter', 'log', 'preview'),
    1 => array('comment_settings', 'menu', 'path', 'captcha', 'field_license', 'field_model_file'), 
  );
  $step = isset($form['#post']['step']) ? (int)$form['#post']['step'] : 0;
  foreach($hidden[$step] as $name) {
    unset($form[$name]);
  }
  $fomr['step'] = array(
    '#type' => 'hidden',
    '#value' => $step + 1,
  );
  $form['#multistep'] = true;
  $form['submit']['#type'] = 'button';
  $form['submit']['#value'] = 'Next';
}

/**
 * Process nodes marked for BRLCAD processing. 
 */
function brlcad_process_nodes() {
  $processingflag = variable_get('brlcad_processing_flag', '');
  $flags = flag_get_user_flags('node', null, 0);
  if(empty($flags[$processingflag])) {
    return;
  }
  foreach($flags[$processingflag] as $nid => $flag) {
    $node = node_load($nid);
    brlcad_process_node($node);
    node_save($node);
  }
}

/**
 * Does BRLCAD processing on a node.
 * @param object $node node to process
 */
function brlcad_process_node(&$node) {
  brlcad_processing_flag($node, false);
  
  // delete old data
  $node->field_dbversion[0]['value'] = '';
  $node->field_title[0]['value'] = '';
  $node->field_units[0]['value'] = '';
  $node->field_summary[0]['value'] = '';
  $node->field_objects[0]['value'] = '';
  
  // delete old images
  if(is_array($node->field_image_file)) {
    foreach($node->field_image_file as $key => $value) {
      if(substr($node->field_image_file[$key]['title'], -7) == ' (auto)') {
        $node->field_image_file[$key]['flags']['delete'] = true;
      }
    }
  }
  
  // obtain model file
  $model = _brlcad_get_node_model($node);
  if(empty($model)) {
    return;  
  }
  
  // prepare environment variables
  $size = (int)variable_get('brlcad_raytrace_size', 512);
  $views = str_replace(array("\r\n", "\n"), ':', variable_get('brlcad_raytrace_ae', ''));
  $image = tempnam(realpath(file_directory_temp()), 'rtimg_');
  $objects = content_transpose_array_rows_cols($node->field_render_objects);
  $objects = empty($objects['value']) ? '*' : implode(' ', $objects['value']);
  $env = array(
    'image' => $image,
    'size' => $size,
    'views' => $views,
    'objects' => $objects, 
  );

  // run the script
  $output = brlcad_mged_run_script('metadata.txt', $model['filepath'], $env);
  unlink($image);
  unset($env);
  if(empty($output) ) {
    return;
  }
  
  // parse the output
  preg_match_all('|DATABASE:([^\n]+)\n(.+)\nDATABASE:\1|sm', $output, $fields);
  $fields = array_combine($fields[1], $fields[2]);
  
  // import metadata values 
  $node->field_dbversion[0]['value'] = isset($fields['VERSION']) ? trim($fields['VERSION']) : '';
  $node->field_title[0]['value'] = isset($fields['TITLE']) ? trim($fields['TITLE']) : '';
  $node->field_units[0]['value'] = isset($fields['UNITS']) ? trim($fields['UNITS']) : '';
  $node->field_summary[0]['value'] = isset($fields['SUMMARY']) ? $fields['SUMMARY'] : '';
  $node->field_objects[0]['value'] = isset($fields['OBJECTS']) ? preg_replace('| +|', ' ', $fields['OBJECTS']) : '';
  
  // import images
  $pixpngcmd = escapeshellcmd(variable_get('brlcad_bin_path', '/usr/brlcad/bin') . '/pix-png') . ' -s ' . $size . ' ';
  $views = explode(':', $views);
  foreach($views as $key => $view) {
    $pixfile = $image . $key . '.pix';
    if(file_exists($pixfile)) {
      $view = $views[$key];
      $pngfile = $image . $key . '.png';
      $cmd = $pixpngcmd  . escapeshellarg($pixfile) . '>' . escapeshellarg($pngfile);
      exec($cmd, $output, $return_var);
      unset($output);
      unlink($pixfile);
      if(!$return_var) {
        $node->field_image_file[] = array(
          'title' => 'View ' . $view . ' (auto)',
          'filename' => str_replace('.', '_', $model['filename']) . '_' . str_replace(' ', '_', $view) . '.png',
          'filepath' => $pngfile,
          'filemime' => file_get_mimetype($pngfile),
          'fid' => 'upload',
          'filesize' => filesize($pngfile),
        );
      } else {
        watchdog('brlcad', t('Failed to execute command %cmd.', array('%cmd' => $cmd)), WATCHDOG_ERROR);
      }
    }  
  }
}

/**
 * Parses the output of one or more BRLCAD's ls -l command. 
 *
 * @param string $text output from BRLCAD
 */
function brlcad_objects_list($text) {
  $text = explode("\n", $text);
  $objects = array();
  foreach($text as $line) {
    if(!preg_match('|^(.+) (\w+) (\d+) (\d+) (\d+)$|', $line, $line)) {
      continue;
    }
    // trim the type suffix for combinations and regions (/ or /R)
    if($suffix = strrpos($name, '/')) {
      $name = substr($name, 0, $suffix);
    }
    $objects[$line[1]] = $line[1] . ';' . $line[2];
  }
  return $objects;
}

function _brlcad_get_node_model(&$node) {
  if(!is_array($node->field_model_file)) {
    return false;
  }
  foreach($node->field_model_file as $value) {
    if(empty($value['delete']) && !empty($value['filepath']) && file_exists($value['filepath'])) {
      return $value;
    }
  }
  return false;
}

function brlcad_mged_run_command($command, $model = null, $env = null, $cwd = null) {
  return _brlcad_mged_run_real_command(escapeshellarg($command), $model, $env, $cwd);
}

function brlcad_mged_run_script($script, $model = null, $env = null, $cwd = null) {
  $script = realpath(drupal_get_path('module', 'brlcad') . '/scripts/' . variable_get('brlcad_version', '') . '/' . $script);
  if(empty($script)) {
    return null;
  }
  return _brlcad_mged_run_real_command('<' . escapeshellarg($script), $model, $env, $cwd);
}


function _brlcad_mged_run_real_command($command, $model = null, $env = null, $cwd = null) {
  $cmd = escapeshellcmd(variable_get('brlcad_bin_path', '/usr/brlcad/bin') . '/mged');
  $cmd .= ' -cr ';
  $model = realpath($model);
  if($model) {
    $model = escapeshellarg($model);
    $cmd .= $model ;
  }
  $cmd .= $command .  ' 2>&1';
  $descriptorspec = array(
    1 => array("pipe", "w"),  // stdout is a pipe that the child will write to
  );
  $process = proc_open($cmd, $descriptorspec, $pipes, $cwd, $env);
  if (!is_resource($process)) {
    watchdog('brlcad', t('Failed to execute command %cmd.', array('%cmd' => $cmd)), WATCHDOG_ERROR);
    return null;
  }
  $output = stream_get_contents($pipes[1]);
  fclose($pipes[1]);

  // It is important that you close any pipes before calling proc_close in order to avoid a deadlock
  $return_value = proc_close($process);
  if($return_value) {
    return null;
  }
  // trim leading warning Opened in READ ONLY mode
  if(substr($output, 0, 24) == 'Opened in READ ONLY mode') {
    $output = substr($output, 25);
  }
  return $output;
}

function _brlcad_fakeuser() {
  static $user;
  if(!isset($user)) {
    $user = (object)array('uid' => 1, 'roles' => array());
  }
  return $user;
}

function _brlcad_supported_versions() {
  static $supported;
  if(!isset($supported)) {
    $supported = glob(drupal_get_path('module', 'brlcad') . '/scripts/*');
    foreach($supported as $key => $value) {
      if(is_dir($value)) {
        $supported[$key] = basename($value);
      } else {
        unset($supported[$key]);
      }
    }
    if(!empty($supported)) {
      $supported = array_combine($supported, $supported);
    }
  }
  return $supported;
}

/**
 * Helper function to be used in CCK fields
 *
 * @return array
 */
function _brlcad_current_node_objects_list() {
  if(arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == 'edit' && ($node = node_load(arg(1)))) {
    return brlcad_objects_list($node->field_objects[0]['value']);
  }
}