<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "BRL-CAD";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath       = "/w";
$wgScriptExtension  = ".php";

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgArticlePath = "/wiki/$1";

$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "MinuteElectron@brlcad.org";
$wgPasswordSender = "MinuteElectron@brlcad.org";

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

require_once('/etc/brlcad/wikisettings.php');

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "TYPE=InnoDB";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageResize      = true;
$wgFileExtensions      = array('png','jpg','jpeg','svn','gif','svg');
$wgUploadPath          = "$wgScriptPath/images";
$wgUploadDirectory     = "$IP/images";
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/etc/brlcad/convert";

$wgSVGConverterPath = '/etc/brlcad';

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "1f8506f970a52aae750b9981693c104e3e23c2082405952f695b1f1867bcd494";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'brlcad2';

# logo for certain error pages
$wgLogo = '../images/logo/BRL-CAD_256x212.png';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

#FIXME: Temp. hack until IP is fixed.
require_once( "$IP/extensions/recaptcha/ReCaptcha.php" );
require_once( "/etc/brlcad/recaptchakeys.php" );
$wgGroupPermissions['user']['skipcaptcha']=true; //allow registered users to skip the captcha triggers
$wgCaptchaTriggers['edit']=true; //force captcha on edit
$wgCaptchaTriggers['create']=true; //force captcha on new page

# let passwords be reset
$wgGroupPermissions['sysop']['passwordreset'] = true;
require_once( "$IP/extensions/PasswordReset/PasswordReset.php" );

# turn on my snazzy CIA notifier extension
$cnProject = 'BRL-CAD';
require_once( "$IP/extensions/CIAnotify/CIAnotify.php" );

# feed settings
$wgFeedLimit = 100; /* num feed results */
$wgFeedCacheTimeout = 0; /* only keep at 0 for debugging */
$wgFeedDiffCutoff = 131072; /* max size of feed diffs */

$wgDiff3 = "/etc/brlcad/diff3";

$wgFileExtensions[] = 'pdf';

$wgUploadSizeWarning = 1048576;

require_once( "$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php" );

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );
	
