<?php
// $Id: widgeditor.module,v 1.1.2.4 2007/07/15 14:01:46 Gurpartap Exp $

function widgeditor_perm() {
  return array('use widgEditor');
}

function widgeditor_menu($maycache) {
  $items = array();

  if ($maycache) {
    $items[] = array(
      'path' => 'admin/settings/widgeditor',
      'title' => t('widgEditor'),
      'description' => t('Describes what the settings generally do.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'widgeditor_admin_settings',
      'access' => user_access('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );
  }

  return $items;
}

function widgeditor_admin_settings() {
  $form = array();

  $form['widgeditor']['widgeditor_default_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t("Enable widgEditor by default"),
    '#default_value' => variable_get('widgeditor_default_enabled', 0),
  );

  return system_settings_form($form);
}

function widgeditor_form_alter($form_id, &$form) {
  $def_enabled = variable_get('widgeditor_default_enabled', 0);
  if (!user_access('use widgEditor')) return;

  if (module_exists('fquery')) {
    $query = f("textarea", $form);
    $textareas = array();
    foreach ($query as $element) {
      $textareas[] = $element['#guid'];
    }
  }
  elseif ($form_id == 'comment_form' || (isset($form['type']) && $form['type']['#value'] .'_node_form' == $form_id)) {
    $textareas = array("edit-body", "edit-comment");
  }

  if (count($textareas) > 0) widgeditor_add_javascript($textareas, $def_enabled);
}

function widgeditor_add_javascript($textareas = array(), $def_enabled) {

  $query = '';
  foreach ($textareas as $i => $ta) {
    $pattern = '/(\d+)-(\w+)/i';
    $replacement = 'edit-$2';
    $query .= "    textareas[$i] = \"" . preg_replace($pattern, $replacement, $ta) . "\";\n";
  }

  drupal_add_js(drupal_get_path('module', 'widgeditor') . '/' . 'scripts/widgEditor.js');
  drupal_add_css(drupal_get_path('module', 'widgeditor') . '/' . 'scripts/css/widgEditor.css');
  if ($def_enabled) {
  drupal_add_js('
if (Drupal.jsEnabled) {
  $(document).ready(function() {
    var textareas = new Array();
' . $query . '
    for (i=0;i<textareas.length;i++) {
      $("textarea#"+textareas[i]).attr("class","widgEditor");
    }
  });
}
', 'inline');}
  else {
    drupal_add_js('
if (Drupal.jsEnabled) {
  $(document).ready(function() {
    var textareas = new Array();
' . $query . '
    for (i=0;i<textareas.length;i++) {
      $("textarea#"+textareas[i]).after(\'<div><a style="cursor: pointer;" id="widgEditor-id" class="widgEditor-\' + textareas[i] +\'">Enable WYSIWYG</a></div>\');
    }
    $("a#widgEditor-id").click(function(){
      var string1= $(this).attr("class");
      var pattern=/(widgEditor)-(\w+)-(\w+)/i;
      if (pattern.test(string1) == true) {
        $("textarea#"+string1.replace(/widgEditor-/, "")).attr("class","widgEditor");
        widgInit();
        $(this).hide("slow");
      }
    });
  });
}
', 'inline');
  }
}
